
[Prefix="mega::"]
interface MegaGfxProcessor
{
    boolean readBitmap(DOMString path);
    long getWidth();
    long getHeight();
    long getBitmapDataSize(long width, long height, long px, long py, long rw, long rh);
    boolean getBitmapData(DOMString bitmapData, long size);
    void freeBitmap();
};

enum ProxyType
{
    "mega::MegaProxy::PROXY_NONE",
    "mega::MegaProxy::PROXY_AUTO",
    "mega::MegaProxy::PROXY_CUSTOM"
};

[Prefix="mega::"]
interface MegaProxy
{
    void setProxyType(long proxyType);
    void setProxyURL(DOMString proxyURL);
    void setCredentials(DOMString username, DOMString password);
    long getProxyType();
    [Const] DOMString getProxyURL();
    boolean credentialsNeeded();
    [Const] DOMString getUsername();
    [Const] DOMString getPassword();
};

[JSImplementation="mega::MegaLogger"]
interface MegaLoggerInterface
{
    void MegaLoggerInterface();
    void log(DOMString time, long loglevel, DOMString source, DOMString message);
};

enum NodeType
{
    "mega::MegaNode::TYPE_UNKNOWN",
    "mega::MegaNode::TYPE_FILE",
    "mega::MegaNode::TYPE_FOLDER",
    "mega::MegaNode::TYPE_ROOT",
    "mega::MegaNode::TYPE_INCOMING",
    "mega::MegaNode::TYPE_RUBBISH"
};

enum NodeChangeType
{
    "mega::MegaNode::CHANGE_TYPE_REMOVED",
    "mega::MegaNode::CHANGE_TYPE_ATTRIBUTES",
    "mega::MegaNode::CHANGE_TYPE_OWNER",
    "mega::MegaNode::CHANGE_TYPE_TIMESTAMP",
    "mega::MegaNode::CHANGE_TYPE_FILE_ATTRIBUTES",
    "mega::MegaNode::CHANGE_TYPE_INSHARE",
    "mega::MegaNode::CHANGE_TYPE_OUTSHARE",
    "mega::MegaNode::CHANGE_TYPE_PARENT",
    "mega::MegaNode::CHANGE_TYPE_PENDINGSHARE"
};

[Prefix="mega::"]
interface MegaNode
{
    long getType();
    [Const] DOMString getName();
    boolean hasCustomAttrs();
    MegaStringList getCustomAttrNames();
    [Const] DOMString getCustomAttr(DOMString attrName);
    DOMString getBase64Handle();
    long getSize();
    long getCreationTime();
    long getModificationTime();
    //MegaHandle getHandle();
    //MegaHandle getParentHandle();
    DOMString getBase64Key();
    long getTag();
    long getExpirationTime();
    //MegaHandle getPublicHandle();
    MegaNode getPublicNode();
    DOMString getPublicLink();
    boolean isFile();
    boolean isFolder();
    boolean isRemoved();
    boolean hasChanged(long changeType);
    long getChanges();
    boolean hasThumbnail();
    boolean hasPreview();
    boolean isPublic();
    boolean isShared();
    boolean isOutShare();
    boolean isInShare();
    boolean isExported();
    boolean isExpired();
    boolean isTakenDown();
};

enum UserVisibility
{
    "mega::MegaUser::VISIBILITY_UNKNOWN",
    "mega::MegaUser::VISIBILITY_HIDDEN",
    "mega::MegaUser::VISIBILITY_VISIBLE",
    "mega::MegaUser::VISIBILITY_ME"
};

enum UserChangeType
{
    "mega::MegaUser::CHANGE_TYPE_AUTH",
    "mega::MegaUser::CHANGE_TYPE_LSTINT",
    "mega::MegaUser::CHANGE_TYPE_AVATAR",
    "mega::MegaUser::CHANGE_TYPE_FIRSTNAME",
    "mega::MegaUser::CHANGE_TYPE_LASTNAME"
};

[Prefix="mega::"]
interface MegaUser
{
    [Const] DOMString getEmail();
    long getVisibility();
    long getTimestamp();
    boolean hasChanged(long changeType);
    long getChanges();
};

enum ShareAccessType
{
    "mega::MegaShare::ACCESS_UNKNOWN",
    "mega::MegaShare::ACCESS_READ",
    "mega::MegaShare::ACCESS_READWRITE",
    "mega::MegaShare::ACCESS_FULL",
    "mega::MegaShare::ACCESS_OWNER"
};

[Prefix="mega::"]
interface MegaShare
{
    [Const] DOMString getUser();
    //MegaHandle getNodeHandle();
    DOMString getBase64Handle();
    long getAccess();
    long getTimestamp();
};

[Prefix="mega::"]
interface MegaStringList
{
    [Const] DOMString get(long i);
    long size();
};

[Prefix="mega::"]
interface MegaNodeList
{
    MegaNode get(long i);
    long size();
};

[Prefix="mega::"]
interface MegaUserList
{
    MegaUser get(long i);
    long size();
};

[Prefix="mega::"]
interface MegaShareList
{
    MegaShare get(long i);
    long size();
};

[Prefix="mega::"]
interface MegaTransferList
{
    MegaTransfer get(long i);
    long size();
};

[Prefix="mega::"]
interface MegaContactRequestList
{
    MegaContactRequest get(long i);
    long size();
};

enum RequestType
{
    "mega::MegaRequest::TYPE_LOGIN",
    "mega::MegaRequest::TYPE_CREATE_FOLDER",
    "mega::MegaRequest::TYPE_MOVE",
    "mega::MegaRequest::TYPE_COPY",
    "mega::MegaRequest::TYPE_RENAME",
    "mega::MegaRequest::TYPE_REMOVE",
    "mega::MegaRequest::TYPE_SHARE",
    "mega::MegaRequest::TYPE_IMPORT_LINK",
    "mega::MegaRequest::TYPE_EXPORT",
    "mega::MegaRequest::TYPE_FETCH_NODES",
    "mega::MegaRequest::TYPE_ACCOUNT_DETAILS",
    "mega::MegaRequest::TYPE_CHANGE_PW",
    "mega::MegaRequest::TYPE_UPLOAD",
    "mega::MegaRequest::TYPE_LOGOUT",
    "mega::MegaRequest::TYPE_GET_PUBLIC_NODE",
    "mega::MegaRequest::TYPE_GET_ATTR_FILE",
    "mega::MegaRequest::TYPE_SET_ATTR_FILE",
    "mega::MegaRequest::TYPE_GET_ATTR_USER",
    "mega::MegaRequest::TYPE_SET_ATTR_USER",
    "mega::MegaRequest::TYPE_RETRY_PENDING_CONNECTIONS",
    "mega::MegaRequest::TYPE_ADD_CONTACT",
    "mega::MegaRequest::TYPE_REMOVE_CONTACT",
    "mega::MegaRequest::TYPE_CREATE_ACCOUNT",
    "mega::MegaRequest::TYPE_CONFIRM_ACCOUNT",
    "mega::MegaRequest::TYPE_QUERY_SIGNUP_LINK",
    "mega::MegaRequest::TYPE_ADD_SYNC",
    "mega::MegaRequest::TYPE_REMOVE_SYNC",
    "mega::MegaRequest::TYPE_REMOVE_SYNCS",
    "mega::MegaRequest::TYPE_PAUSE_TRANSFERS",
    "mega::MegaRequest::TYPE_CANCEL_TRANSFER",
    "mega::MegaRequest::TYPE_CANCEL_TRANSFERS",
    "mega::MegaRequest::TYPE_DELETE",
    "mega::MegaRequest::TYPE_REPORT_EVENT",
    "mega::MegaRequest::TYPE_CANCEL_ATTR_FILE",
    "mega::MegaRequest::TYPE_GET_PRICING",
    "mega::MegaRequest::TYPE_GET_PAYMENT_ID",
    "mega::MegaRequest::TYPE_GET_USER_DATA",
    "mega::MegaRequest::TYPE_LOAD_BALANCING",
    "mega::MegaRequest::TYPE_KILL_SESSION",
    "mega::MegaRequest::TYPE_SUBMIT_PURCHASE_RECEIPT",
    "mega::MegaRequest::TYPE_CREDIT_CARD_STORE",
    "mega::MegaRequest::TYPE_UPGRADE_ACCOUNT",
    "mega::MegaRequest::TYPE_CREDIT_CARD_QUERY_SUBSCRIPTIONS",
    "mega::MegaRequest::TYPE_CREDIT_CARD_CANCEL_SUBSCRIPTIONS",
    "mega::MegaRequest::TYPE_GET_SESSION_TRANSFER_URL",
    "mega::MegaRequest::TYPE_GET_PAYMENT_METHODS",
    "mega::MegaRequest::TYPE_INVITE_CONTACT",
    "mega::MegaRequest::TYPE_REPLY_CONTACT_REQUEST",
    "mega::MegaRequest::TYPE_SUBMIT_FEEDBACK",
    "mega::MegaRequest::TYPE_SEND_EVENT",
    "mega::MegaRequest::TYPE_CLEAN_RUBBISH_BIN",
    "mega::MegaRequest::TYPE_SET_ATTR_NODE"
};

[Prefix="mega::"]
interface MegaRequest
{
    long getType();
    [Const] DOMString getRequestString();
    //DOMString toString();
    //MegaHandle getNodeHandle();
    DOMString getBase64NodeHandle();
    [Const] DOMString getLink();
    //MegaHandle getParentHandle();
    DOMString getParentBase64Handle();
    [Const] DOMString getSessionKey();
    [Const] DOMString getName();
    [Const] DOMString getEmail();
    [Const] DOMString getPassword();
    [Const] DOMString getNewPassword();
    [Const] DOMString getPrivateKey();
    long getAccess();
    [Const] DOMString getFile();
    long getNumRetry();
    MegaNode getPublicNode();
    MegaNode getPublicMegaNode();
    long getParamType();
    [Const] DOMString getText();
    long getNumber();
    boolean getFlag();
    long getTransferredBytes();
    long getTotalBytes();
    //MegaRequestListener getListener();
    MegaAccountDetails getMegaAccountDetails();
    MegaPricing getPricing();
    long getTransferTag();
    long getNumDetails();
    long getTag();
};

enum TransferType
{
    "mega::MegaTransfer::TYPE_DOWNLOAD",
    "mega::MegaTransfer::TYPE_UPLOAD"
};
    
[Prefix="mega::"]
interface MegaTransfer
{
    long getType();
    [Const] DOMString getTransferString();
    //DOMString toString();
    long getStartTime();
    long getTransferredBytes();
    long getTotalBytes();
    [Const] DOMString getPath();
    [Const] DOMString getParentPath();

    //MegaHandle getNodeHandle();
    DOMString getBase64NodeHandle();

    //MegaHandle getParentHandle();
    DOMString getParentBase64Handle();

    long getStartPos();
    long getEndPos();
    [Const] DOMString getFileName();
    //MegaTransferListener getListener();
    long getNumRetry();
    long getMaxRetries();
    long getTag();
    long getSpeed();
    long getDeltaSize();
    long getUpdateTime();
    MegaNode getPublicMegaNode();
    boolean isSyncTransfer();
    boolean isStreamingTransfer();
    VoidPtr getLastBytes();
    boolean isFolderTransfer();
    long getFolderTransferTag();
};

enum ContactRequestState
{
    "mega::MegaContactRequest::STATUS_UNRESOLVED",
    "mega::MegaContactRequest::STATUS_ACCEPTED",
    "mega::MegaContactRequest::STATUS_DENIED",
    "mega::MegaContactRequest::STATUS_IGNORED",
    "mega::MegaContactRequest::STATUS_DELETED",
    "mega::MegaContactRequest::STATUS_REMINDED"
};

enum ContactRequestReplyType
{
    "mega::MegaContactRequest::REPLY_ACTION_ACCEPT",
    "mega::MegaContactRequest::REPLY_ACTION_DENY",
    "mega::MegaContactRequest::REPLY_ACTION_IGNORE"
};

enum ContactRequestAction
{
    "mega::MegaContactRequest::INVITE_ACTION_ADD",
    "mega::MegaContactRequest::INVITE_ACTION_DELETE",
    "mega::MegaContactRequest::INVITE_ACTION_REMIND"
};

[Prefix="mega::"]
interface MegaContactRequest
{
    //MegaHandle getHandle();
    DOMString getBase64Handle();

    DOMString getSourceEmail();
    DOMString getSourceMessage();
    DOMString getTargetEmail();
    long getCreationTime();
    long getModificationTime();
    long getStatus();
    boolean isOutgoing();
};

enum ErrorType
{
    "mega::MegaError::API_OK",
    "mega::MegaError::API_EINTERNAL",
    "mega::MegaError::API_EARGS",
    "mega::MegaError::API_EAGAIN",
    "mega::MegaError::API_ERATELIMIT",
    "mega::MegaError::API_EFAILED",
    "mega::MegaError::API_ETOOMANY",
    "mega::MegaError::API_ERANGE",
    "mega::MegaError::API_EEXPIRED",
    "mega::MegaError::API_ENOENT",
    "mega::MegaError::API_ECIRCULAR",
    "mega::MegaError::API_EACCESS",
    "mega::MegaError::API_EEXIST",
    "mega::MegaError::API_EINCOMPLETE",
    "mega::MegaError::API_EKEY",
    "mega::MegaError::API_ESID",
    "mega::MegaError::API_EBLOCKED",
    "mega::MegaError::API_EOVERQUOTA",
    "mega::MegaError::API_ETEMPUNAVAIL",
    "mega::MegaError::API_ETOOMANYCONNECTIONS",
    "mega::MegaError::API_EWRITE",
    "mega::MegaError::API_EREAD",
    "mega::MegaError::API_EAPPKEY",
    "mega::MegaError::API_ESSL",

    "mega::MegaError::PAYMENT_ECARD",
    "mega::MegaError::PAYMENT_EBILLING",
    "mega::MegaError::PAYMENT_EFRAUD",
    "mega::MegaError::PAYMENT_ETOOMANY",
    "mega::MegaError::PAYMENT_EBALANCE",
    "mega::MegaError::PAYMENT_EGENERIC"
};

[Prefix="mega::"]
interface MegaError
{
    void MegaError(long errorCode);
    long getErrorCode();
    [Const] DOMString getErrorString();
    //DOMString toString();
    //static DOMString getErrorString(long errorCode);
};

[JSImplementation="mega::MegaTreeProcessor"]
interface MegaTreeProcessorInterface
{
    void MegaTreeProcessorInterface();
    boolean processMegaNode(MegaNode node);
};

[JSImplementation="mega::MegaRequestListener"]
interface MegaRequestListenerInterface
{
    void MegaRequestListenerInterface();
    void onRequestStart(MegaApi api, MegaRequest request);
    void onRequestFinish(MegaApi api, MegaRequest request, MegaError e);
    void onRequestUpdate(MegaApi api, MegaRequest request);
    void onRequestTemporaryError(MegaApi api, MegaRequest request, MegaError error);
};

[JSImplementation="mega::MegaTransferListener"]
interface MegaTransferListenerInterface
{
    void MegaTransferListenerInterface();
    void onTransferStart(MegaApi api, MegaTransfer transfer);
    void onTransferFinish(MegaApi api, MegaTransfer transfer, MegaError error);
    void onTransferUpdate(MegaApi api, MegaTransfer transfer);
    void onTransferTemporaryError(MegaApi api, MegaTransfer transfer, MegaError error);
    boolean onTransferData(MegaApi api, MegaTransfer transfer, DOMString buffer, long size);
};

[JSImplementation="mega::MegaGlobalListener"]
interface MegaGlobalListenerInterface
{
    void MegaGlobalListenerInterface();
    void onUsersUpdate(MegaApi api, MegaUserList users);
    void onNodesUpdate(MegaApi api, MegaNodeList nodes);
    void onAccountUpdate(MegaApi api);
    void onContactRequestsUpdate(MegaApi api, MegaContactRequestList requests);
    void onReloadNeeded(MegaApi api);
};

[JSImplementation="mega::MegaListener"]
interface MegaListenerInterface
{
    void MegaListenerInterface();
    void onRequestStart(MegaApi api, MegaRequest request);
    void onRequestFinish(MegaApi api, MegaRequest request, MegaError e);
    void onRequestUpdate(MegaApi api, MegaRequest request);
    void onRequestTemporaryError(MegaApi api, MegaRequest request, MegaError error);
    void onTransferStart(MegaApi api, MegaTransfer transfer);
    void onTransferFinish(MegaApi api, MegaTransfer transfer, MegaError error);
    void onTransferUpdate(MegaApi api, MegaTransfer transfer);
    void onTransferTemporaryError(MegaApi api, MegaTransfer transfer, MegaError error);
    void onUsersUpdate(MegaApi api, MegaUserList users);
    void onNodesUpdate(MegaApi api, MegaNodeList nodes);
    void onAccountUpdate(MegaApi api);
    void onContactRequestsUpdate(MegaApi api, MegaContactRequestList requests);
    void onReloadNeeded(MegaApi api);
};

/*
[JSImplementation="mega::MegaInputStream"]
interface MegaInputStreamInterface
{
    void MegaInputStreamInterface();
    long getSize();
    boolean read(DOMString buffer, long size);
};
*/

/*
enum int
{
    "mega::MegaApi::STATE_NONE",
    "mega::MegaApi::STATE_SYNCED",
    "mega::MegaApi::STATE_PENDING",
    "mega::MegaApi::STATE_SYNCING",
    "mega::MegaApi::STATE_IGNORED"
};*/

enum LogLevel
{
    "mega::MegaApi::LOG_LEVEL_FATAL",
    "mega::MegaApi::LOG_LEVEL_ERROR",
    "mega::MegaApi::LOG_LEVEL_WARNING",
    "mega::MegaApi::LOG_LEVEL_INFO",
    "mega::MegaApi::LOG_LEVEL_DEBUG",
    "mega::MegaApi::LOG_LEVEL_MAX"
};

enum FileAttrType
{
    "mega::MegaApi::ATTR_TYPE_THUMBNAIL",
    "mega::MegaApi::ATTR_TYPE_PREVIEW"
};

enum UserAttrType
{
    "mega::MegaApi::USER_ATTR_AVATAR",
    "mega::MegaApi::USER_ATTR_FIRSTNAME",
    "mega::MegaApi::USER_ATTR_LASTNAME",
    "mega::MegaApi::USER_ATTR_AUTHRING",
    "mega::MegaApi::USER_ATTR_LAST_INTERACTION"
};

enum PaymentMethod
{
    "mega::MegaApi::PAYMENT_METHOD_BALANCE",
    "mega::MegaApi::PAYMENT_METHOD_PAYPAL",
    "mega::MegaApi::PAYMENT_METHOD_ITUNES",
    "mega::MegaApi::PAYMENT_METHOD_GOOGLE_WALLET",
    "mega::MegaApi::PAYMENT_METHOD_BITCOIN",
    "mega::MegaApi::PAYMENT_METHOD_UNIONPAY",
    "mega::MegaApi::PAYMENT_METHOD_FORTUMO",
    "mega::MegaApi::PAYMENT_METHOD_CREDIT_CARD",
    "mega::MegaApi::PAYMENT_METHOD_CENTILI"
};

enum TransferMethod
{
    "mega::MegaApi::TRANSFER_METHOD_NORMAL",
    "mega::MegaApi::TRANSFER_METHOD_ALTERNATIVE_PORT",
    "mega::MegaApi::TRANSFER_METHOD_AUTO"
};

enum SortOrder
{
    "mega::MegaApi::ORDER_NONE",
    "mega::MegaApi::ORDER_DEFAULT_ASC",
    "mega::MegaApi::ORDER_DEFAULT_DESC",
    "mega::MegaApi::ORDER_SIZE_ASC",
    "mega::MegaApi::ORDER_SIZE_DESC",
    "mega::MegaApi::ORDER_CREATION_ASC",
    "mega::MegaApi::ORDER_CREATION_DESC",
    "mega::MegaApi::ORDER_MODIFICATION_ASC",
    "mega::MegaApi::ORDER_MODIFICATION_DESC",
    "mega::MegaApi::ORDER_ALPHABETICAL_ASC",
    "mega::MegaApi::ORDER_ALPHABETICAL_DESC"
};

[Prefix="mega::"]
interface MegaApi
{
    void MegaApi(DOMString appKey, DOMString basePath, DOMString userAgent);
    void MegaApi(DOMString appKey, MegaGfxProcessor processor, DOMString basePath, DOMString userAgent);
    void addListener(MegaListenerInterface listener);
    void addRequestListener(MegaRequestListenerInterface listener);
    void addTransferListener(MegaTransferListenerInterface listener);
    void addGlobalListener(MegaGlobalListenerInterface listener);
    void removeListener(MegaListenerInterface listener);
    void removeRequestListener(MegaRequestListenerInterface listener);
    void removeTransferListener(MegaTransferListenerInterface listener);
    void removeGlobalListener(MegaGlobalListenerInterface listener);
    MegaRequest getCurrentRequest();
    MegaTransfer getCurrentTransfer();
    MegaError getCurrentError();
    MegaNodeList getCurrentNodes();
    MegaUserList getCurrentUsers();
    DOMString getBase64PwKey(DOMString password);
    DOMString getStringHash(DOMString base64pwkey, DOMString email);
    void getSessionTransferURL(DOMString path, MegaRequestListenerInterface listener);
    //static MegaHandle base32ToHandle(DOMString base32Handle);
    //static MegaHandle base64ToHandle(DOMString base64Handle);
    //static DOMString handleToBase64(MegaHandle handle);
    //static DOMString userHandleToBase64(MegaHandle handle);
    static void addEntropy(DOMString data, unsigned long size);
    void retryPendingConnections(boolean disconnect, boolean includexfers, MegaRequestListenerInterface listener);
    void login(DOMString email, DOMString password, MegaRequestListenerInterface listener);
    void loginToFolder(DOMString megaFolderLink, MegaRequestListenerInterface listener);
    void fastLogin(DOMString email, DOMString stringHash, DOMString base64pwkey, MegaRequestListenerInterface listener);
    void fastLogin(DOMString session, MegaRequestListenerInterface listener);
    //void killSession(MegaHandle sessionHandle, MegaRequestListenerInterface listener);
    void killSession(DOMString sessionHandle, MegaRequestListenerInterface listener);
    void getUserData(MegaRequestListenerInterface listener);
    void getUserData(MegaUser user, MegaRequestListenerInterface listener);
    //void getUserData(DOMString user, MegaRequestListenerInterface listener);
    DOMString dumpSession();
    DOMString dumpXMPPSession();
    void createAccount(DOMString email, DOMString password, DOMString name, MegaRequestListenerInterface listener);
    void fastCreateAccount(DOMString email, DOMString base64pwkey, DOMString name, MegaRequestListenerInterface listener);
    void querySignupLink(DOMString link, MegaRequestListenerInterface listener);
    void confirmAccount(DOMString link, DOMString password, MegaRequestListenerInterface listener);
    void fastConfirmAccount(DOMString link, DOMString base64pwkey, MegaRequestListenerInterface listener);
    void setProxySettings(MegaProxy proxySettings);
    MegaProxy getAutoProxySettings();
    long isLoggedIn();
    DOMString getMyEmail();
    DOMString getMyUserHandle();
    static void setLogLevel(long logLevel);
    static void setLoggerObject(MegaLoggerInterface megaLogger);
    static void log(long logLevel, DOMString message, DOMString filename, long line);
    void createFolder(DOMString name, MegaNode parent, MegaRequestListenerInterface listener);
    void moveNode(MegaNode node, MegaNode newParent, MegaRequestListenerInterface listener);
    void copyNode(MegaNode node, MegaNode newParent, MegaRequestListenerInterface listener);
    void copyNode(MegaNode node, MegaNode newParent, DOMString newName, MegaRequestListenerInterface listener);
    void renameNode(MegaNode node, DOMString newName, MegaRequestListenerInterface listener);
    void remove(MegaNode node, MegaRequestListenerInterface listener);
    void cleanRubbishBin(MegaRequestListenerInterface listener);
    //void sendFileToUser(MegaNode node, MegaUser user, MegaRequestListenerInterface listener);
    void sendFileToUser(MegaNode node, DOMString email, MegaRequestListenerInterface listener);
    //void share(MegaNode node, MegaUser user, long level, MegaRequestListenerInterface listener);
    void share(MegaNode node, DOMString email, long level, MegaRequestListenerInterface listener);
    void importFileLink(DOMString megaFileLink, MegaNode parent, MegaRequestListenerInterface listener);
    void getPublicNode(DOMString megaFileLink, MegaRequestListenerInterface listener);
    void getThumbnail(MegaNode node, DOMString dstFilePath, MegaRequestListenerInterface listener);
    void getPreview(MegaNode node, DOMString dstFilePath, MegaRequestListenerInterface listener);
    void getUserAvatar(MegaUser user, DOMString dstFilePath, MegaRequestListenerInterface listener);
    //void getUserAvatar(DOMString dstFilePath, MegaRequestListenerInterface listener);
    void getUserAttribute(MegaUser user, long type, MegaRequestListenerInterface listener);
    void getUserAttribute(long type, MegaRequestListenerInterface listener);
    void cancelGetThumbnail(MegaNode node, MegaRequestListenerInterface listener);
    void cancelGetPreview(MegaNode node, MegaRequestListenerInterface listener);
    void setThumbnail(MegaNode node, DOMString srcFilePath, MegaRequestListenerInterface listener);
    void setPreview(MegaNode node, DOMString srcFilePath, MegaRequestListenerInterface listener);
    void setAvatar(DOMString srcFilePath, MegaRequestListenerInterface listener);
    void setUserAttribute(long type, DOMString value, MegaRequestListenerInterface listener);
    void setCustomNodeAttribute(MegaNode node, DOMString attrName, DOMString value,  MegaRequestListenerInterface listener);
    void exportNode(MegaNode node, MegaRequestListenerInterface listener);
    void exportNode(MegaNode node, long expireTime, MegaRequestListenerInterface listener);
    void disableExport(MegaNode node, MegaRequestListenerInterface listener);
    void fetchNodes(MegaRequestListenerInterface listener);
    void getAccountDetails(MegaRequestListenerInterface listener);
    void getExtendedAccountDetails(boolean sessions, boolean purchases, boolean transactions, MegaRequestListenerInterface listener);
    void getPricing(MegaRequestListenerInterface listener);
    //void getPaymentId(MegaHandle productHandle, MegaRequestListenerInterface listener);
    void getPaymentId(DOMString productHandle, MegaRequestListenerInterface listener);
    //void upgradeAccount(MegaHandle productHandle, long paymentMethod, MegaRequestListenerInterface listener);
    void upgradeAccount(DOMString productHandle, long paymentMethod, MegaRequestListenerInterface listener);
    void submitPurchaseReceipt(DOMString receipt, MegaRequestListenerInterface listener);
    void submitPurchaseReceipt(long gateway, DOMString receipt, MegaRequestListenerInterface listener);
    void creditCardStore(DOMString address1, DOMString address2, DOMString city,
                         DOMString province, DOMString country, DOMString postalcode,
                         DOMString firstname, DOMString lastname, DOMString creditcard,
                         DOMString expire_month, DOMString expire_year, DOMString cv2,
                         MegaRequestListenerInterface listener);


    void creditCardQuerySubscriptions(MegaRequestListenerInterface listener);
    void creditCardCancelSubscriptions(DOMString reason, MegaRequestListenerInterface listener);
    void getPaymentMethods(MegaRequestListenerInterface listener);
    DOMString exportMasterKey();
    void changePassword(DOMString oldPassword, DOMString newPassword, MegaRequestListenerInterface listener);
    void addContact(DOMString email, MegaRequestListenerInterface listener);
    void inviteContact(DOMString email, DOMString message, long action, MegaRequestListenerInterface listener);
    void replyContactRequest(MegaContactRequest request, long action, MegaRequestListenerInterface listener);
    //void removeContact(MegaUser user, MegaRequestListenerInterface listener);
    void removeContact(DOMString email, MegaRequestListenerInterface listener);
    void logout(MegaRequestListenerInterface listener);
    void localLogout(MegaRequestListenerInterface listener);
    void submitFeedback(long rating, DOMString comment, MegaRequestListenerInterface listener);
    void sendEvent(long eventType, DOMString message, MegaRequestListenerInterface listener);
    void reportDebugEvent(DOMString text, MegaRequestListenerInterface listener);

    ///////////////////   TRANSFERS ///////////////////
    void startUpload(DOMString localPath, MegaNode parent, MegaTransferListenerInterface listener);
    //void startUpload(DOMString localPath, MegaNode parent, long mtime, MegaTransferListenerInterface listener);
    void startUpload(DOMString localPath, MegaNode parent, DOMString fileName, MegaTransferListenerInterface listener);
    void startUpload(DOMString localPath, MegaNode parent, DOMString fileName, long mtime, MegaTransferListenerInterface listener);
    void startDownload(MegaNode node, DOMString localPath, MegaTransferListenerInterface listener);
    void startStreaming(MegaNode node, long startPos, long size, MegaTransferListenerInterface listener);
    void cancelTransfer(MegaTransfer transfer, MegaRequestListenerInterface listener);
    void cancelTransferByTag(long transferTag, MegaRequestListenerInterface listener);
    void cancelTransfers(long type, MegaRequestListenerInterface listener);
    void pauseTransfers(boolean pause, MegaRequestListenerInterface listener);
    void pauseTransfers(boolean pause, long direction, MegaRequestListenerInterface listener);
    boolean areTransfersPaused(long direction);
    void setUploadLimit(long bpslimit);
    void setDownloadMethod(long method);
    void setUploadMethod(long method);
    long getDownloadMethod();
    long getUploadMethod();
    MegaTransferList getTransfers();
    MegaTransferList getStreamingTransfers();
    MegaTransfer getTransferByTag(long transferTag);
    MegaTransferList getTransfers(long type);
    MegaTransferList getChildTransfers(long transferTag);
    void update();
    boolean isWaiting();
    long getNumPendingUploads();
    long getNumPendingDownloads();
    long getTotalUploads();
    long getTotalDownloads();
    void resetTotalDownloads();
    void resetTotalUploads();
    long getTotalDownloadedBytes();
    long getTotalUploadedBytes();
    void updateStats();

    long getNumChildren(MegaNode parent);
    long getNumChildFiles(MegaNode parent);
    long getNumChildFolders(MegaNode parent);
    MegaNodeList getChildren(MegaNode parent, long order);
    long getIndex(MegaNode node, long order);
    MegaNode getChildNode(MegaNode parent, DOMString name);
    MegaNode getParentNode(MegaNode node);
    DOMString getNodePath(MegaNode node);
    MegaNode getNodeByPath(DOMString path, MegaNode n);
    //MegaNode getNodeByHandle(MegaHandle h);
    MegaNode getNodeByBase64Handle(DOMString h);
    //MegaContactRequest getContactRequestByHandle(MegaHandle handle);
    MegaContactRequest getContactRequestByBase64Handle(DOMString handle);
    MegaUserList getContacts();
    MegaUser getContact(DOMString email);
    MegaNodeList getInShares(MegaUser user);
    MegaNodeList getInShares();
    MegaShareList getInSharesList();
    boolean isShared(MegaNode node);
    boolean isOutShare(MegaNode node);
    boolean isInShare(MegaNode node);
    boolean isPendingShare(MegaNode node);
    MegaShareList getOutShares();
    MegaShareList getOutShares(MegaNode node);
    MegaShareList getPendingOutShares();
    MegaShareList getPendingOutShares(MegaNode node);
    MegaContactRequestList getIncomingContactRequests();
    MegaContactRequestList getOutgoingContactRequests();
    long getAccess(MegaNode node);
    long getSize(MegaNode node);
    //DOMString getFingerprint(DOMString filePath);
    DOMString getFingerprint(MegaNode node);
    //DOMString getFingerprint(MegaInputStreamInterface inputStream, long mtime);
    MegaNode getNodeByFingerprint(DOMString fingerprint);
    MegaNode getNodeByFingerprint(DOMString fingerprint, MegaNode parent);
    boolean hasFingerprint(DOMString fingerprint);
    //DOMString getCRC(DOMString filePath);
    DOMString getCRCFromFingerprint(DOMString fingerprint);
    DOMString getCRC(MegaNode node);
    MegaNode getNodeByCRC(DOMString crc, MegaNode parent);
    long checkAccess(DOMString handle, long level);
    long checkMove(DOMString node, DOMString target);
    //MegaError checkAccess(MegaNode node, long level);
    //MegaError checkMove(MegaNode node, MegaNode target);
    MegaNode getRootNode();
    MegaNode getInboxNode();
    MegaNode getRubbishNode();
    MegaNodeList search(MegaNode node, DOMString searchString, boolean recursive);
    boolean processMegaTree(MegaNode node, MegaTreeProcessorInterface processor, boolean recursive);
    //MegaNode createPublicFileNode(MegaHandle handle, DOMString key, DOMString name,
    //                               long size, long mtime, MegaHandle parentHandle, DOMString auth);
    //MegaNode createPublicFolderNode(MegaHandle handle, DOMString name, MegaHandle parentHandle, DOMString auth);
    [Const] DOMString getVersion();
    [Const] DOMString getUserAgent();
    void changeApiUrl(DOMString apiURL, boolean disablepkp);
    DOMString escapeFsIncompatible(DOMString filename);
    DOMString unescapeFsIncompatible(DOMString name);
    boolean createThumbnail(DOMString imagePath, DOMString dstPath);
    boolean createPreview(DOMString imagePath, DOMString dstPath);
    static DOMString base64ToBase32(DOMString base64);
    static DOMString base32ToBase64(DOMString base32);
    void loadBalancing(DOMString service, MegaRequestListenerInterface listener);
    static DOMString strdup(DOMString buffer);
    static void removeRecursively(DOMString path);
    boolean isOnline();
};

//[Prefix="mega::"]
//interface MegaHashSignature
//{
//    MegaHashSignature(DOMString base64Key);
//    void init();
//    void add(DOMString data, unsigned size);
//    boolean checkSignature(DOMString base64Signature);
//};

[Prefix="mega::"]
interface MegaAccountBalance
{
    double getAmount();
    [Const] DOMString getCurrency();
};

[Prefix="mega::"]
interface MegaAccountSession
{
    long getCreationTimestamp();
    long getMostRecentUsage();
    DOMString getUserAgent();
    DOMString getIP();
    DOMString getCountry();
    boolean isCurrent();
    boolean isAlive();
    //MegaHandle getHandle();
    DOMString getBase64Handle();
};

[Prefix="mega::"]
interface MegaAccountPurchase
{
    long getTimestamp();
    DOMString getHandle();
    DOMString getCurrency();
    double getAmount();
    long getMethod();
};

[Prefix="mega::"]
interface MegaAccountTransaction
{
    long getTimestamp();
    DOMString getHandle();
    DOMString getCurrency();
    double getAmount();
};

enum AccountType
{
    "mega::MegaAccountDetails::ACCOUNT_TYPE_FREE",
    "mega::MegaAccountDetails::ACCOUNT_TYPE_PROI",
    "mega::MegaAccountDetails::ACCOUNT_TYPE_PROII",
    "mega::MegaAccountDetails::ACCOUNT_TYPE_PROIII",
    "mega::MegaAccountDetails::ACCOUNT_TYPE_LITE"
};

enum SubscriptionStatus
{
    "mega::MegaAccountDetails::SUBSCRIPTION_STATUS_NONE",
    "mega::MegaAccountDetails::SUBSCRIPTION_STATUS_VALID",
    "mega::MegaAccountDetails::SUBSCRIPTION_STATUS_INVALID"
};

[Prefix="mega::"]
interface MegaAccountDetails
{
    long getProLevel();
    long getProExpiration();
    long getSubscriptionStatus();
    long getSubscriptionRenewTime();
    DOMString getSubscriptionMethod();
    DOMString getSubscriptionCycle();
    long getStorageMax();
    long getStorageUsed();
    long getTransferMax();
    long getTransferOwnUsed();
    long getNumUsageItems();

    //long getStorageUsed(MegaHandle handle);
    //long getNumFiles(MegaHandle handle);
    //long getNumFolders(MegaHandle handle);
    long getStorageUsed(DOMString handle);
    long getNumFiles(DOMString handle);
    long getNumFolders(DOMString handle);

    long getNumBalances();
    MegaAccountBalance getBalance(long i);
    long getNumSessions();
    MegaAccountSession getSession(long i);
    long getNumPurchases();
    MegaAccountPurchase getPurchase(long i);
    long getNumTransactions();
    MegaAccountTransaction getTransaction(long i);

    //[EnforceRange] attribute long long storage_max;
};

[Prefix="mega::"]
interface MegaPricing
{
    long getNumProducts();
    //MegaHandle getHandle(long productIndex);
    DOMString getBase64Handle(long productIndex);
    long getProLevel(long productIndex);
    long getGBStorage(long productIndex);
    long getGBTransfer(long productIndex);
    long getMonths(long productIndex);
    long getAmount(long productIndex);
    [Const] DOMString getCurrency(long productIndex);
    [Const] DOMString getDescription(long productIndex);
    [Const] DOMString getIosID(long productIndex);
    [Const] DOMString getAndroidID(long productIndex);
};
